//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHRM.itdoseBridge {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="itdoseBridge.IITDoseDataServiceBridge")]
    public interface IITDoseDataServiceBridge {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/LIS_FillUnit", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/LIS_FillUnitResponse")]
        System.Data.DataSet LIS_FillUnit(out string processInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/LIS_AmountOfTestPerformedByLab", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/LIS_AmountOfTestPerformedByLabRespons" +
            "e")]
        System.Data.DataSet LIS_AmountOfTestPerformedByLab(string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/LIS_ContractAnalysisOfUnit", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/LIS_ContractAnalysisOfUnitResponse")]
        System.Data.DataSet LIS_ContractAnalysisOfUnit(out string processInfo, string unitId, string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/LIS_ContractAnalysisItemWise", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/LIS_ContractAnalysisItemWiseResponse")]
        System.Data.DataSet LIS_ContractAnalysisItemWise(out string processInfo, string unitId, string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/ExecuteDataset", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/ExecuteDatasetResponse")]
        System.Data.DataSet ExecuteDataset(out string result, string commandText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/ExecuteScalar", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/ExecuteScalarResponse")]
        string ExecuteScalar(string qry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/HIS_IPDValidation", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/HIS_IPDValidationResponse")]
        string HIS_IPDValidation(string IPDNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/HIS_PaymentDetail", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/HIS_PaymentDetailResponse")]
        string HIS_PaymentDetail(string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/HIS_In_PatientDetail", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/HIS_In_PatientDetailResponse")]
        string HIS_In_PatientDetail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/HIS_ConsolidateSale", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/HIS_ConsolidateSaleResponse")]
        System.Data.DataSet HIS_ConsolidateSale(string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/HIS_DataForTeleCaller", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/HIS_DataForTeleCallerResponse")]
        string HIS_DataForTeleCaller(string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITDoseDataServiceBridge/NoDuseEmployee", ReplyAction="http://tempuri.org/IITDoseDataServiceBridge/NoDuseEmployeeResponse")]
        string NoDuseEmployee(string emp_code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IITDoseDataServiceBridgeChannel : eHRM.itdoseBridge.IITDoseDataServiceBridge, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ITDoseDataServiceBridgeClient : System.ServiceModel.ClientBase<eHRM.itdoseBridge.IITDoseDataServiceBridge>, eHRM.itdoseBridge.IITDoseDataServiceBridge {
        
        public ITDoseDataServiceBridgeClient() {
        }
        
        public ITDoseDataServiceBridgeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ITDoseDataServiceBridgeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ITDoseDataServiceBridgeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ITDoseDataServiceBridgeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LIS_FillUnit(out string processInfo) {
            return base.Channel.LIS_FillUnit(out processInfo);
        }
        
        public System.Data.DataSet LIS_AmountOfTestPerformedByLab(string from, string to) {
            return base.Channel.LIS_AmountOfTestPerformedByLab(from, to);
        }
        
        public System.Data.DataSet LIS_ContractAnalysisOfUnit(out string processInfo, string unitId, string from, string to) {
            return base.Channel.LIS_ContractAnalysisOfUnit(out processInfo, unitId, from, to);
        }
        
        public System.Data.DataSet LIS_ContractAnalysisItemWise(out string processInfo, string unitId, string from, string to) {
            return base.Channel.LIS_ContractAnalysisItemWise(out processInfo, unitId, from, to);
        }
        
        public System.Data.DataSet ExecuteDataset(out string result, string commandText) {
            return base.Channel.ExecuteDataset(out result, commandText);
        }
        
        public string ExecuteScalar(string qry) {
            return base.Channel.ExecuteScalar(qry);
        }
        
        public string HIS_IPDValidation(string IPDNo) {
            return base.Channel.HIS_IPDValidation(IPDNo);
        }
        
        public string HIS_PaymentDetail(string from, string to) {
            return base.Channel.HIS_PaymentDetail(from, to);
        }
        
        public string HIS_In_PatientDetail() {
            return base.Channel.HIS_In_PatientDetail();
        }
        
        public System.Data.DataSet HIS_ConsolidateSale(string from, string to) {
            return base.Channel.HIS_ConsolidateSale(from, to);
        }
        
        public string HIS_DataForTeleCaller(string from, string to) {
            return base.Channel.HIS_DataForTeleCaller(from, to);
        }
        
        public string NoDuseEmployee(string emp_code) {
            return base.Channel.NoDuseEmployee(emp_code);
        }
    }
}
